server:
  port: 8105

spring:
  data:
    redis:
      host: localhost
      port: 6381
  cache:
    type: redis

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: EmailWithAttachmentDTO:com.bank.web.app.download.kafka.EmailWithAttachmentDTO


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: ALWAYS

resilience4j:
  circuitbreaker:
    instances:
      downloadService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 7s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  ratelimiter:
    instances:
      downloadRateLimiter:
        limit-refresh-period: 5s
        limit-for-period: 10
        timeout-duration: 1s
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 1
    instances:
      downloadBulkheadService:
        maxConcurrentCalls: 1
        maxWaitDuration: 0

kafkaTopic:
  requestStatement: RequestStatementTopic
